# Generated by Django 3.2.7 on 2025-12-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
