# Generated by Django 3.2.7 on 2025-12-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
